development:
  adapter: postgresql
  database: brew_chat_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: brew_chat_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: brew_chat_production
  pool: 5
  timeout: 5000
